### ISSUE TITLE
too-busy is a dev dependency

### ISSUE THREAD

**Issue by djabraham** [dcolens/connect-ready#1]
Wasn't sure if it was intentional?

**Comment by dcolens** [comment]
yes it is, because toobusy is optional, maybe I should make it clearer in the readme, thanks for the feedback :)

**Comment by Hirse** [comment]
Maybe this is a case for an [npm optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies)?

**Comment by dcolens** [comment]
Cool, I did not know of optional dependencies :) I'm not sure it applies here because the feature is used when a module can handle the absence of the module, while in this case, if a user enables `ready.enableTooBusy(70)` and too busy is not installed it will throw and error.
I'll update the README about this.

**Comment by dcolens** [comment]
My main concern about including toobusy-js is that in many case folks won't need it and I like keeping things lean, is it very annoying ?

**Comment by Hirse** [comment]
I would think adding it as optional dependency makes it semantically clear what the relation between the packages is. It doesn't remove the need for documentation though. 😉 
Throwing an error when requesting a not installed optional dependency seems valid to me.
If you don't want it to break, logging a warning with a link to your readme would be an alternative.

**Comment by dcolens** [comment]
it is now an optionalDependencies.
